// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAST3oAkBsjCguv1D0N1-5AiuUGC7GeNko',
    appId: '1:351885806060:web:c35842bf7eaa69607118c9',
    messagingSenderId: '351885806060',
    projectId: 'voting-app-ddc31',
    authDomain: 'voting-app-ddc31.firebaseapp.com',
    storageBucket: 'voting-app-ddc31.firebasestorage.app',
    measurementId: 'G-90RQCNXYH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9kq3WS9aKjj0vSpmBxyECw8XzBBOmHh8',
    appId: '1:351885806060:android:50be7421405e22a87118c9',
    messagingSenderId: '351885806060',
    projectId: 'voting-app-ddc31',
    storageBucket: 'voting-app-ddc31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuKnELe3jmKQJkmuZKJSL668VTbOFh4B0',
    appId: '1:351885806060:ios:6ab88ad48b4614f57118c9',
    messagingSenderId: '351885806060',
    projectId: 'voting-app-ddc31',
    storageBucket: 'voting-app-ddc31.firebasestorage.app',
    iosBundleId: 'com.example.votingApp',
  );
}
